// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnKwPZesGAD_GjPMdkpOHQkIXOfBc1Drs',
    appId: '1:52620996606:android:02555cded42637a7089aaf',
    messagingSenderId: '52620996606',
    projectId: 'tp2-gestion-de-taches-f3a5e',
    storageBucket: 'tp2-gestion-de-taches-f3a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHvMniIJWhprLmdUokeECM0nMOpr0GOP4',
    appId: '1:52620996606:ios:7514263f663fcaff089aaf',
    messagingSenderId: '52620996606',
    projectId: 'tp2-gestion-de-taches-f3a5e',
    storageBucket: 'tp2-gestion-de-taches-f3a5e.appspot.com',
    iosClientId: '52620996606-32t80etoi8p443pqk4b2v2ubtg0hdoeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHvMniIJWhprLmdUokeECM0nMOpr0GOP4',
    appId: '1:52620996606:ios:40bb0fc56fbeb174089aaf',
    messagingSenderId: '52620996606',
    projectId: 'tp2-gestion-de-taches-f3a5e',
    storageBucket: 'tp2-gestion-de-taches-f3a5e.appspot.com',
    iosClientId: '52620996606-8jvvh92tau2oet0mvnp7h54u5uqh9p0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tp2.RunnerTests',
  );
}
